Repository puppetlabs/puppetlabs-puppetdb, pull requests merged in 2024-02, with the labels that each got.

#371 Fix: Unterminated quoted string when creating read user
  manifests/database/default_read_grant.pp
  spec/support/unit/shared/database.rb
Labels: bugfix

#372 (BACKWARDS-INCOMPATIBLE) Update firewall manifests to use `jump` instead of `action`
  .fixtures.yml
  manifests/server/firewall.pp
  metadata.json
  spec/support/unit/shared/server.rb
Labels: backwards-incompatible, needs-rebase, hacktoberfest

#391 Update postgresql connection validation
  manifests/server/validate_db.pp
  manifests/server/validate_read_db.pp
  spec/unit/classes/server/validate_db_spec.rb
  spec/unit/classes/server/validate_read_db_spec.rb
Labels: maintenance

#392 Fix custom database port support
  manifests/database/default_read_grant.pp
  manifests/database/postgresql.pp
  manifests/database/read_grant.pp
  manifests/database/read_only_user.pp
  spec/acceptance/standalone_spec.rb
  spec/defines/database/default_read_grant_spec.rb
  spec/defines/database/read_grant_spec.rb
  spec/defines/database/read_only_user_spec.rb
  spec/support/acceptance/shared/puppetdb.rb
  spec/unit/classes/database/postgresql_spec.rb
Labels: bugfix
