Repository puppetlabs/puppetlabs-puppetdb, pull requests merged in 2024-04, with the labels that each got.

#399 Archive CHANGELOG.md
  HISTORY.md
Labels: maintenance

#357 Remove obsolete database config options
  REFERENCE.md
  manifests/init.pp
  manifests/params.pp
  manifests/server.pp
  manifests/server/database.pp
  manifests/server/read_database.pp
  spec/unit/classes/server/database_ini_spec.rb
  spec/unit/classes/server/read_database_ini_spec.rb
Labels: backwards-incompatible

#400 Support scram-sha-256 password_encryption method
  manifests/database/postgresql.pp
  manifests/database/read_only_user.pp
  manifests/init.pp
  manifests/params.pp
  metadata.json
  spec/unit/classes/init_spec.rb
Labels: bugfix
