Repository puppetlabs/puppetlabs-puppetdb, pull requests merged in 2024-05, with the labels that each got.

#402 Fix lower bound the of puppetlabs-postgresql dependency
  metadata.json
Labels: bugfix, community

#404 Add a `puppetdb_version` fact with PuppetDB version
  lib/facter/puppetdb_version.rb
  spec/unit/facter/puppetdb_version_spec.rb
Labels: feature, community

#343 Restrict configuration file permissions
  manifests/server.pp
  manifests/server/database.pp
  manifests/server/jetty.pp
  manifests/server/puppetdb.pp
  manifests/server/read_database.pp
  spec/unit/classes/server/database_ini_spec.rb
  spec/unit/classes/server/jetty_ini_spec.rb
  spec/unit/classes/server/puppetdb_ini_spec.rb
  spec/unit/classes/server/read_database_ini_spec.rb
  spec/unit/classes/server_spec.rb
Labels: enhancement, community

#321 cron puppetdb-dlo-cleanup requires package
  manifests/server.pp
Labels: bugfix

#359 set encoding when creating the DB
  manifests/database/postgresql.pp
  spec/unit/classes/database/postgresql_spec.rb
Labels: bugfix, community

#320 Hide passwords from output
  manifests/server/database.pp
  manifests/server/read_database.pp
  spec/unit/classes/server/database_ini_spec.rb
  spec/unit/classes/server/read_database_ini_spec.rb
Labels: enhancement, community

#408 Target release-any-tag workflows
  .github/workflows/ci.yml
  .github/workflows/labeller.yml
  .github/workflows/mend.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/release_prep.yml
  .github/workflows/release_without.yml
  CODEOWNERS
Labels: maintenance

#331 Allow `Sensitive` data type for secrets
  REFERENCE.md
  manifests/database/postgresql.pp
  manifests/database/read_only_user.pp
  manifests/init.pp
  manifests/server.pp
  manifests/server/database.pp
  manifests/server/read_database.pp
  manifests/server/validate_db.pp
  manifests/server/validate_read_db.pp
Labels: feature, needs-tests

#410 (maint) update cat workflows
  .github/workflows/ci.yml
  .github/workflows/mend.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/release_prep.yml
  .github/workflows/release_without.yml
Labels: maintenance
